language: php

sudo: false

php:
  - 5.6
  - 7.1
  - 7.2
  - 7.3

before_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - composer install

script:
  - composer validate --strict
  - vendor/bin/codecept run unit --coverage-xml

after_script:
  - php ocular.phar code-coverage:upload --format=php-clover tests/_output/coverage.xml
