name: PHP Composer

on:
   - push
   - pull_request

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: composer:v2

      - name: Validate composer
        run: composer validate --strict

      - name: Install
        run: composer install --prefer-dist --no-progress

      - name: Unit Test
        run: vendor/bin/codecept run unit
