name: PHP Composer

on:
   - push
   - pull_request

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Validate composer
        run: composer validate --strict

      - name: Composer cache
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys:
            ${{ runner.os }}-php-

      - name: Install
        run: composer install --prefer-dist --no-progress

      - name: Unit Test
        run: vendor/bin/codecept run unit --coverage-xml
